services:
  movie-api:
    env_file:
      - ../.env
    container_name: movie-api
    build:
      context: ../
      dockerfile: services/movie-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - movie-db
    environment:
      GIN_MODE: release
      DB_HOST: ${MOVIE_DB_HOST}
      DB_PORT: ${MOVIE_DB_PORT}
      DB_USER: ${MOVIE_DB_USER}
      DB_PASSWORD: ${MOVIE_DB_PASSWORD}
      DB_NAME: ${MOVIE_DB_NAME}
      PORT: 8080
    networks:
      - cinema-network

  movie-db:
    env_file:
      - ../.env
    container_name: movie-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${MOVIE_DB_USER}
      POSTGRES_PASSWORD: ${MOVIE_DB_PASSWORD}
      POSTGRES_DB: ${MOVIE_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_movie_data:/var/lib/postgresql/data
    networks:
      - cinema-network

volumes:
  postgres_movie_data:

networks:
  cinema-network:
    driver: bridge
